### ISSUE TITLE
Is this project maintained? (YES)

### ISSUE THREAD

**Issue by mondeja** [eduardogr/google-drive-python#7]
Hi. I've used your code in my production environment to synchronize some reports to a Google Drive account, but to do that I've rewritten some parts of the code adding functionality like uploading and removing files. Apart from that, the current implementation is poor and lacks even the `click` dependency.

Are you maintaining this project or should I fork it?

**Comment by eduardogr** [comment]
hello @mondeja  please, feel free to open a PR with the changes you would like to add.

thanks for your interest

**Comment by eduardogr** [comment]
@mondeja thanks for your observations i've fixed the missing requirements and release a new version with them.

Feel free to open new issues and  Pull Request with the things you would like to add.

I would appreciate if we add one thing at a time in small and traceable PRs.

Thanks! 🙏🏽

**Comment by mondeja** [comment]
Sorry, but I've rewritten the whole codebase. Are you using this in a production environment or is just a hobby project?

**Comment by eduardogr** [comment]
yes, it is in use.

Don't be sorry, each one proceeds as needed or knows or preferred
